docker:
  dialect: postgres
  datasource:
      host=storage
      dbname=postgres
      user=postgres
      password=password
      sslmode=disable
  dir: /app/migrations/postgres
# development:
#   dialect: postgres
#   datasource:
#       host=storage
#       dbname=postgres
#       user=postgres
#       password=password
#       sslmode=disable
#   dir: /projects/medods/migrations/postgres/
